arb-dir: lib/l10n/arb
template-arb-file: it.arb
output-localization-file: product_catalog_localizations.dart
output-class: ProductCatalogLocalizations
nullable-getter: false
synthetic-package: false
output-dir: lib/l10n/delegates
untranslated-messages-file: lib/l10n/untranslated_messages.json