name: product_catalog
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  bloc: ^9.0.0
  bloc_test: ^10.0.0
  dio: ^5.8.0+1
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.1.0
  fpdart: ^1.1.1
  get_it: ^8.0.3
  intl: ^0.20.2
  json_annotation: ^4.9.0
  logger: ^2.5.0
  mocktail: ^1.0.4
  shimmer: ^3.0.0

dev_dependencies:
  build_runner: ^2.4.15
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  import_sorter: ^4.6.0
  json_serializable: ^6.9.5
  very_good_analysis: ^7.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - lib/assets/fonts/
    - lib/assets/icons/

  fonts:
    - family: Poppins
      fonts:
        - asset: lib/assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: lib/assets/fonts/Poppins-SemiBold.ttf
          weight: 600

import_sorter:
  comments: false
  ignored_files:
    - lib/l10n/*
